# Generated by Django 5.2.5 on 2025-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_alter_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/default-post.jpg', null=True, upload_to='cover_photos'),
        ),
    ]
