# Generated by Django 5.2.5 on 2025-09-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_alter_profile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
    ]
